version: 0.2
env:
  variables:
    REPOSITORY_URI: "207567753841.dkr.ecr.ap-south-1.amazonaws.com/webappsource"
phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $REPOSITORY_URI
  build:
    commands:
      - docker build -t $REPOSITORY_URI:latest .
  post_build:
    commands:
      - docker push $REPOSITORY_URI:latest
